app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'UserController@login');
Route::put('login', 'UserController@attempt');
Route::get('logout', 'UserController@logout');
Route::get('user/edit', 'UserController@edit');
Route::put('user/edit', 'UserController@update');

Route::resource('user', 'UserController', ['except' => ['edit', 'update', 'destroy']]);
Route::resource('post', 'PostController');
Route::resource('comment', 'CommentController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'content', 'user_id'
    ];

    /**
     * The comments added to post.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    /**
     * The author of the post.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Auth;
use Illuminate\Http\Request;

use App\Http\Requests;

class PostController extends Controller
{
    /**
     * CommentController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', [
            'except' => ['index', 'show']
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('post.index', [
            'posts' => Post::with('user')->orderBy('created_at', 'desc')->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|min:6',
            'content' => 'required|min:40',
        ]);

        $post = new Post($request->all());
        //$post->user()->associate(Auth::user());
        $post->saveOrFail();

        return redirect()
            ->route('post.show', $post->id)
            ->with('notify', 'Post created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('post.show', [
            'post' => Post::findOrFail($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $this->authorize('update', $post);

        return view('post.edit', [
            'post' => $post
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        $this->authorize('update', $post);

        $this->validate($request, [
            'title' => 'required|min:6',
            'content' => 'required|min:40',
        ]);

        $post->fill($request->only([
            'title', 'content'
        ]));
        $post->saveOrFail();

        return redirect()
            ->route('post.show', $post->id)
            ->with('notify', 'Post updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        if($post->delete()) {
            return redirect()
                ->route('post.index')
                ->with('notify', 'Post deleted');
        }

        return redirect()
            ->route('post.index');
    }
}

resources/views/post/create.blade.php
@extends('layouts.default')
@section('title', 'Write post')

@section('content')
    <div class="uk-container-center">
        <form class="uk-form uk-margin-top" method="post" action="{{ route('post.store') }}">
            {{ csrf_field() }}
            {{ method_field('post') }}
            <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">

            @if(count($errors) > 0)
                <div class="uk-alert uk-alert-danger">
                    <strong> There are some errors: </strong>
                    <ul class="uk-margin-top-remove">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="uk-form-row">
                <label class="uk-form-label"> Title: </label>
                <div class="uk-form-controls">
                    <input class="uk-form-width-large" type="text" name="title" value="{{ old('title') }}">
                </div>
            </div>

            <div class="uk-form-row">
                <label class="uk-form-label"> Content: </label>
                <div class="uk-form-controls">
                    <textarea class="uk-width-1-1" type="text" name="content">{{ old('content') }}</textarea>
                </div>
            </div>

            <div class="uk-form-row">
                <input class="uk-button" type="submit" name="submit" value="Submit">
            </div>
        </form>
    </div>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.default')
@section('title', 'Edit post')

@section('content')
    <div class="uk-container-center">
        <form class="uk-form uk-margin-top" method="post" action="{{ route('post.update', $post->id) }}">
            {{ csrf_field() }}
            {{ method_field('put') }}

            @if(count($errors) > 0)
                <div class="uk-alert uk-alert-danger">
                    <strong> There are some errors: </strong>
                    <ul class="uk-margin-top-remove">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="uk-form-row">
                <label class="uk-form-label"> Title: </label>
                <div class="uk-form-controls">
                    <input class="uk-form-width-large" type="text" name="title" value="{{ old('title', $post->title) }}">
                </div>
            </div>

            <div class="uk-form-row">
                <label class="uk-form-label"> Content: </label>
                <div class="uk-form-controls">
                    <textarea class="uk-width-1-1" type="text" name="content">{{ old('content', $post->content) }}</textarea>
                </div>
            </div>

            <div class="uk-form-row">
                <input class="uk-button" type="submit" name="submit" value="Submit">
            </div>
        </form>
    </div>
@endsection

resources/views/post/index.blade.php
@extends('layouts.default')
@section('title', 'Posts')

@section('content')
    <div class="uk-text-right uk-margin-top">
        <a class="uk-button" href="{{ route('post.create') }}"> Write post </a>
    </div>

    @if(count($posts) == 0)
        <h1> Upss... </h1>
        <p> There aren't any post yet, be first - <a href="{{ route('post.create') }}">write sth</a>! </p>
    @endif

    <div class="uk-margin-top uk-margin-large-bottom">
        @foreach($posts as $post)
            <article class="uk-article">
                <h1 class="uk-article-title">{{ $post->title }}</h1>
                <p class="uk-article-meta">Written by <a
                            href="{{ route('user.show', $post->user->id) }}">{{ $post->user->name }}</a>
                    on {{ $post->created_at }}.</p>
                <p class="uk-article-lead">{{ str_limit(strip_tags($post->content)) }} <a
                            href="{{ route('post.show', $post->id) }}"> read more </a></p>
            </article>
        @endforeach
    </div>

    @include('layouts.elements.pagination', ['paginator' => $posts])
@endsection

resources/views/post/show.blade.php
@extends('layouts.default')
@section('title', $post->title)

@section('content')
    @if(Auth::check() && Auth::user()->id == $post->user_id)
        <div class="uk-text-right uk-margin-top">
            <a class="uk-button" href="{{ route('post.edit', $post->id) }}"> Edit </a>
            <form class="uk-display-inline" action="{{ route('post.destroy', $post->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('delete') }}
                <button type="submit" class="uk-button"> Delete </button>
            </form>
        </div>
    @endif

    <div class="uk-margin-large-top uk-margin-large-bottom">
        <article class="uk-article">
            <h1 class="uk-article-title">{{ $post->title }}</h1>
            <p class="uk-article-meta">Written by <a
                        href="{{ route('user.show', $post->user->id) }}">{{ $post->user->name }}</a>
                on {{ $post->created_at }}.</p>
            <p class="uk-article-lead">{!! $post->content !!}</p>
        </article>
    </div>
@endsection