app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'UserController@login');
Route::put('login', 'UserController@attempt');
Route::get('logout', 'UserController@logout');
Route::get('user/edit', 'UserController@edit');
Route::put('user/edit', 'UserController@update');

Route::resource('user', 'UserController', ['except' => ['edit', 'update', 'destroy']]);
Route::resource('post', 'PostController');
Route::resource('comment', 'CommentController');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The posts added by user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts() {
        return $this->hasMany('App\Post');
    }

    /**
     * The comments added by user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments() {
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Auth;
use DB;
use Hash;
use Illuminate\Http\Request;

use App\Http\Requests;

class UserController extends Controller
{
    /**
     * UserController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', [
            'except' => ['login', 'attempt', 'create', 'store', 'logout']
        ]);
    }

    /**
     * Show the login form.
     *
     * @return \Illuminate\Http\Response
     */
    public function login()
    {
        return view('user.login');
    }

    /**
     * Attempt to login user.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function attempt(Request $request)
    {
        $email = $request->email;
        $password = $request->password;

        if (!Auth::attempt(['email' => $email, 'password' => $password])) {
            return back()
                ->withInput()
                ->with('error', 'Invalid credentials');
        }

        return redirect()
            ->intended(route('post.index'));
    }

    /**
     * Logout current user.
     *
     * @return \Illuminate\Http\Response
     */
    public function logout()
    {
        Auth::logout();

        return redirect()
            ->action('UserController@login');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.index', [
            'users' => User::orderBy('name')->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|alpha_dash',
            'email' => 'required|email|unique:users',
            'password' => 'required|confirmed'
        ]);

        $user = new User($request->only(['name', 'email']));
        $user->password = Hash::make($request->password);
        $user->saveOrFail();

        Auth::login($user);

        return redirect()
            ->route('post.index')
            ->with('notify', 'Account created, you are logged in');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('user.show', [
            'user' => (object)(DB::select(DB::raw("select * from users where id='$id'"))[0])
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        $user = Auth::user();
        $this->authorize('update', $user);

        return view('user.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $user = Auth::user();
        $this->authorize('update', $user);

        $this->validate($request, [
            'password' => 'required|confirmed'
        ]);

        $user->password = Hash::make($request->password);
        $user->saveOrFail();

        return redirect()
            ->route('user.show', $user->id)
            ->with('notify', 'Account updated');
    }
}

resources/views/user/create.blade.php
@extends('layouts.default')
@section('title', 'Create account')

@section('content')
    <div class="uk-width-small-1-2 uk-width-medium-1-4 uk-container-center">
        <form class="uk-form uk-margin-large-top" method="post" action="{{ route('user.store') }}">
            {{ csrf_field() }}
            {{ method_field('post') }}

            @if(count($errors) > 0)
                <div class="uk-alert uk-alert-danger">
                    <strong> There are some errors: </strong>
                    <ul class="uk-margin-top-remove">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="uk-form-row">
                <label class="uk-form-label"> Name: </label>
                <div class="uk-form-controls">
                    <input class="uk-width-1-1" type="text" name="name" value="{{ old('name') }}">
                </div>
            </div>

            <div class="uk-form-row">
                <label class="uk-form-label"> E-Mail: </label>
                <div class="uk-form-controls">
                    <input class="uk-width-1-1" type="text" name="email" value="{{ old('email') }}">
                </div>
            </div>

            <div class="uk-form-row">
                <label class="uk-form-label"> Password: </label>
                <div class="uk-form-controls">
                    <input class="uk-width-1-1" type="password" name="password" value="{{ old('password') }}">
                </div>
            </div>

            <div class="uk-form-row">
                <label class="uk-form-label"> Confirm password: </label>
                <div class="uk-form-controls">
                    <input class="uk-width-1-1" type="password" name="password_confirmation">
                </div>
            </div>

            <div class="uk-form-row">
                <input class="uk-button" type="submit" name="submit" value="Register">
            </div>
        </form>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.default')
@section('title', 'Edit account')

@section('content')
    <div class="uk-width-small-1-2 uk-width-medium-1-4 uk-container-center">
        <form class="uk-form uk-margin-large-top" method="post" action="{{ action('UserController@update') }}">
            {{ method_field('put') }}

            @if(count($errors) > 0)
                <div class="uk-alert uk-alert-danger">
                    <strong> There are some errors: </strong>
                    <ul class="uk-margin-top-remove">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="uk-form-row">
                <label class="uk-form-label"> Password: </label>
                <div class="uk-form-controls">
                    <input class="uk-width-1-1" type="password" name="password" value="{{ old('password') }}">
                </div>
            </div>

            <div class="uk-form-row">
                <label class="uk-form-label"> Confirm password: </label>
                <div class="uk-form-controls">
                    <input class="uk-width-1-1" type="password" name="password_confirmation">
                </div>
            </div>

            <div class="uk-form-row">
                <input class="uk-button" type="submit" name="submit" value="Update">
            </div>
        </form>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.default')
@section('title', 'Users')

@section('content')
    <table class="uk-table uk-table-striped uk-margin-top">
        <thead>
        <tr>
            <th class="uk-width-1-10"> #</th>
            <th> Name</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td><a href="{{ route('user.show', $user->id) }}">{{ $user->name }}</a></td>
            </tr>
        @endforeach
        </tbody>
    </table>

    @include('layouts.elements.pagination', ['paginator' => $users])
@endsection

resources/views/user/login.blade.php
@extends('layouts.default')
@section('title', 'Login')

@section('content')
    <div class="uk-width-small-1-2 uk-width-medium-1-4 uk-container-center">
        <form class="uk-form uk-margin-large-top" method="post" action="{{ action('UserController@login') }}">
            {{ csrf_field() }}
            {{ method_field('put') }}

            @if(session()->has('error'))
                <div class="uk-alert uk-alert-danger">{{ session('error') }}</div>
            @endif

            <div class="uk-form-row">
                <label class="uk-form-label"> E-Mail: </label>
                <div class="uk-form-controls">
                    <input class="uk-width-1-1" type="text" name="email" value="{{ old('email') }}">
                </div>
            </div>

            <div class="uk-form-row">
                <label class="uk-form-label"> Password: </label>
                <div class="uk-form-controls">
                    <input class="uk-width-1-1" type="password" name="password">
                </div>
            </div>

            <div class="uk-form-row">
                <input class="uk-button" type="submit" name="submit" value="Login">
            </div>
        </form>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.default')
@section('title', $user->name)

@section('content')
    <table class="uk-table uk-margin-top">
        <tr>
            <th class="uk-width-1-10"> Id </th>
            <td>{{ $user->id }}</td>
        </tr>
        <tr>
            <th class="uk-width-1-10"> E-Mail </th>
            <td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th class="uk-width-1-10"> Name </th>
            <td>{{ $user->name }}</td>
        </tr>
    </table>

    @if(Auth::user()->id == $user->id)
        <a class="uk-button" href="{{ action('UserController@edit') }}"> Change password </a>
    @endif
@endsection