app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'UserController@login');
Route::put('login', 'UserController@attempt');
Route::get('logout', 'UserController@logout');
Route::get('user/edit', 'UserController@edit');
Route::put('user/edit', 'UserController@update');

Route::resource('user', 'UserController', ['except' => ['edit', 'update', 'destroy']]);
Route::resource('post', 'PostController');
Route::resource('comment', 'CommentController');

resources/views/layouts/elements/navbar.blade.php
<nav class="uk-navbar uk-navbar-attached">
    <div class="uk-container uk-container-center">
        <div>
            <ul class="uk-navbar-nav">
                <li><a href="{{ url('/') }}"> Home </a></li>
                <li><a href="{{ route('post.index') }}"> Posts </a></li>
                @if(Auth::check())
                    <li><a href="{{ route('user.index') }}"> Users </a></li>
                @endif
            </ul>
        </div>

        <div class="uk-navbar-flip">
            <ul class="uk-navbar-nav">
                @if(Auth::check())
                    <li><a href="{{ route('user.show', Auth::user()->id) }}"> Profile </a></li>
                    <li><a href="{{ action('UserController@logout') }}"> Logout </a></li>
                @else
                    <li><a href="{{ action('UserController@login') }}"> Login </a></li>
                    <li><a href="{{ route('user.create') }}"> Register </a></li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/elements/pagination.blade.php
@if ($paginator->lastPage() > 1)
    <ul class="uk-pagination">
        @if($paginator->currentPage() == 1)
            <li class="uk-disabled"><span><i class="uk-icon-angle-left"></i></span></li>
        @else
            <li><a href="{{ $paginator->url($paginator->currentPage() - 1) }}"><i class="uk-icon-angle-left"></i></a></li>
        @endif

        @for ($i = 1; $i <= $paginator->lastPage(); $i++)
            @if($paginator->currentPage() == $i)
                <li class="uk-active"><span>{{ $i }}</span></li>
            @else
                <li><a href="{{ $paginator->url($i) }}">{{ $i }}</a></li>
            @endif
        @endfor

        @if($paginator->currentPage() == $paginator->lastPage())
            <li class="uk-disabled"><span><i class="uk-icon-angle-right"></i></span></li>
        @else
            <li><a href="{{ $paginator->url($paginator->currentPage() + 1) }}"><i class="uk-icon-angle-right"></i></a></li>
        @endif
    </ul>
@endif